services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin 
    pull_policy: always
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@explore-ufos.me
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
       - traefik
       - backend
    ports:
      - "80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.explore-ufos.me`)
      - traefik.http.routers.pgadmin.entrypoints=https
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=simple-resolver
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

volumes:
  pgadmin_data:
    driver: local

networks:
  traefik:
      name: traefik
      external: true
  backend:
      external: true
